### ISSUE TITLE
Erroneous command names in README.md

### ISSUE THREAD

**Issue by elWanderero** [Volumental/django-leek#12]
In [Getting Started](https://github.com/Volumental/django-leek/blob/master/README.md#getting-started) in the README there are two slight syntax typos:

1. Under point 2 it should be `django_leek` that goes in `settings.py`, not `django-leek`.
2. Under point 4 the command to run the server is `leek` not `runleek`

**Comment by vidstige** [comment]
Very much correct, thank you.
